### ISSUE TITLE
Keyerror 2

### ISSUE THREAD

**Issue by Sc0rp11** [M4cs/BabySploit#21]
I just tried to install BabySploit on my nethunter device. Everything went OK. Until i tried to start uo BabySploit i get this error.

Traceback (most recent call last):
  File "/usr/local/bin/babysploit", line 11, in <module>        load_entry_point('babysploit==1.1.19', 'console_scripts', 'babysploit')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()                                          File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/babysploit-1.1.19-py3.6.egg/babysploit/__main__.py", line 15, in <module>  File "/usr/local/lib/python3.6/dist-packages/babysploit-1.1.19-py3.6.egg/babysploit/display.py", line 9, in welcome
KeyError: 2
root@kali:~/BabySploit#

**Comment by M4cs** [comment]
What verrsion of Python3 is ths?

**Comment by Sc0rp11** [comment]
@m4cs Python3.6

**Comment by M4cs** [comment]
Try running python -m babysploit

**Comment by Sc0rp11** [comment]
@m4cs No module named babysploit. Also tried python3 -m. Same keyerror

**Comment by M4cs** [comment]
Did you install via Pip?

**Comment by Sc0rp11** [comment]
@M4cs no. Installed with git

**Comment by M4cs** [comment]
Try installing via pip

**Comment by Sc0rp11** [comment]
Then I get this 

Last login: Sun Jan 13 22:34:59 CET 2019 on pts/2
Linux kali 3.4.112-cyanogenmod-g8fbc62e #3 SMP PREEMPT Fri Aug 12 19:57:27 CDT 2016 armv7l

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Traceback (most recent call last):
  File "/usr/local/bin/babysploit", line 6, in <module>
    from babysploit.__main__ import main
  File "/usr/local/lib/python3.6/dist-packages/babysploit/__main__.py", line 15, in <module>                                display.welcome()
  File "/usr/local/lib/python3.6/dist-packages/babysploit/display.py", line 9, in welcome
    gw = gateways['default'][AF_INET][0]                    KeyError: 2


@m4cs

**Comment by M4cs** [comment]
Try running `pip3 install --upgrade --no-cache-dir babysploit` and then `babysploit`

**Comment by Sc0rp11** [comment]
That worked ! Thanks
